"""add field address

Revision ID: bc6eba310e3b
Revises: 6ac32df55eed
Create Date: 2024-07-14 05:44:20.823694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bc6eba310e3b"
down_revision: Union[str, None] = "6ac32df55eed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "address")
    # ### end Alembic commands ###
